services:
  - type: web
    name: gotcg-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGO_URI
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_B64
        sync: false
      - key: CLIENT_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
