services:
  - type: web
    name: gotcg-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: NODE_ENV
        value: production        # OK (not synced)
      - key: PORT
        value: 8080              # OK (not synced)

      - key: MONGO_URI
        sync: false              # OK (synced/secret -> NO value)

      - key: CLIENT_URL
        sync: false              # OK (synced -> NO value)

      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false              # OK (synced -> NO value)