/// <reference lib="webworker" />
declare const self: ServiceWorkerGlobalScope;

// This file is not currently used. The service worker is auto-generated by vite-plugin-pwa.
// Notifications are handled directly from the React app using the Notification API.

export {};