services:
  - type: web
    name: gotcg-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: CLIENT_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
